### ISSUE TITLE
Keine Funktion des Buttons Warenkorb

### ISSUE THREAD

**Issue by mstaber** [agenturtriebwerk/BulkOrderDoku#11]
Ich habe die aktuelle Version in einem Shopware 5.0.3 System laufen. Nach Auswahl der einzelnen Produkte in der Ansicht funktioniert der Link "In den Warenkorb" nicht. Die url ist shop.culture-thetrend.de

Vielen Dank für Ihre Mühen und eine Lösung.

Manuel Staber

**Comment by mstaber** [comment]
Ich bins nochmal. Haben Sie eine Lösung für mich?!? Es funktioniert noch immer nicht und ich benötige die Funktion.

Danke sehr.

**Comment by agenturtriebwerk** [comment]
Die Pluginversion wurde mit 5.1 erfolgreich getestet und ist nun dafür im shopware Store freigeschalten.
