### ISSUE TITLE
Fehlende Aktualisierung beim Hinzufügen in den Warenkorb

### ISSUE THREAD

**Issue by cosmoshop** [agenturtriebwerk/BulkOrderDoku#7]
Hallo Agenturtriebwerk,

ein Kunde setzt Shopware 4.3.2 mit eurem Plugin in der Version 1.0.2 ein.

Nun gibt es folgendes Problem: 

Bei einer Bestellung von mehreren Artikeln in der Bulk-Ansicht und beim Klick auf den "In den Wahrenkorb" gibt es keinerlei Rückmeldung.

Auch der Wahrenkorbbestand im Header wird nicht aktualisiert. 

Kann es sein dass das ein Fehler im Plugin ist oder muss dafür etwas angepasst werden?

**Comment by agenturtriebwerk** [comment]
Nach Telefonischer Abstimmung war das Problem nicht reproduzierbar.
