### ISSUE TITLE
Eingabe der Artikelmengen per Hand ermöglichen

### ISSUE THREAD

**Issue by cosmoshop** [agenturtriebwerk/BulkOrderDoku#8]
Hallo Agenturtriebwerk,

könntet ihr in dem Plugin die Auswahl der Artikelmengen statt durch Dropdowns durch einfache Eingabefelder ersetzen?
Dadurch könnte die Seite um einiges schneller geladen werden, da sehr viel weniger HTML-Code übertragen werden. 

Ich würde mich sehr über eine mögliche Umsetzung freuen.

**Comment by agenturtriebwerk** [comment]
Die Auswahl der Artikelmenge über Dropdown bleibt mittelfristig die angebotene Methode, da diese robuster gegen Fehleingaben ist und ggf. Mengenbeschränkungen abbildet.

Eine Individualisierung ist jederzeit möglich. Kontaktieren Sie hierfür shopware@agentur-triebwerk.de
